# Generated by Django 4.2.11 on 2024-05-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0002_participant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='document_type',
            field=models.CharField(blank=True, choices=[('employment_contract', 'Arbeidsovereenkomst'), ('bank_statement', 'Bankafschrift'), ('birth_certificate', 'Geboorteakte'), ('proof_of_address', 'Bewijs van Adres'), ('tax_documents', 'Belastingdocumenten'), ('educational_certificates', 'Onderwijscertificaten'), ('immigration_documents', 'Immigratiedocumenten'), ('health_insurance_card', 'Zorgverzekeringskaart'), ('rental_agreement', 'Huurcontract'), ('marriage_certificate', 'Huwelijksakte'), ('id_card', 'Identiteitskaart'), ('insurance_policies', 'Verzekeringspolissen'), ('medical_records', 'Medische dossiers'), ('utility_bill', 'Nutskostenrekening'), ('passport', 'Paspoort'), ('residence_permit', 'Verblijfsvergunning'), ('drivers_license', 'Rijbewijs'), ('social_security_card', 'Socialezekerheidskaart'), ('vehicle_registration', 'Kentekenbewijs'), ('work_permit', 'Werkvergunning')], max_length=30, null=True),
        ),
    ]
