# Generated by Django 4.2.11 on 2024-05-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0003_participant_document_date_participant_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='custom_document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
