# Generated by Django 4.2.11 on 2024-05-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0004_participant_custom_document_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('first_name', 'last_name', 'date_of_birth')},
        ),
    ]
