# Generated by Django 4.2.11 on 2024-05-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0005_alter_participant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='document_type',
            field=models.CharField(choices=[('employment_contract', 'Arbeidsovereenkomst'), ('bank_statement', 'Bankafschrift'), ('birth_certificate', 'Geboorteakte'), ('proof_of_address', 'Bewijs van Adres'), ('tax_documents', 'Belastingdocumenten'), ('educational_certificates', 'Onderwijscertificaten'), ('immigration_documents', 'Immigratiedocumenten'), ('health_insurance_card', 'Zorgverzekeringskaart'), ('rental_agreement', 'Huurcontract'), ('marriage_certificate', 'Huwelijksakte'), ('id_card', 'Identiteitskaart'), ('insurance_policies', 'Verzekeringspolissen'), ('medical_records', 'Medische dossiers'), ('utility_bill', 'Nutskostenrekening'), ('passport', 'Paspoort'), ('residence_permit', 'Verblijfsvergunning'), ('drivers_license', 'Rijbewijs'), ('social_security_card', 'Socialezekerheidskaart'), ('vehicle_registration', 'Kentekenbewijs'), ('work_permit', 'Werkvergunning'), ('other', 'other')], default='id_card', max_length=30),
            preserve_default=False,
        ),
    ]
