# Generated by Django 4.2.11 on 2024-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Beheerder', 'Beheerder'), ('Medewerker', 'Medewerker'), ('Vrijwilliger', 'Vrijwilliger'), ('Supervisor', 'Supervisor'), ('Coördinator', 'Coördinator'), ('Manager', 'Manager'), ('Directeur', 'Directeur')], default='Medewerker', max_length=250, verbose_name='Rol medewerker'),
        ),
    ]
