# Generated by Django 4.2.11 on 2024-05-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('Notes', '0002_note_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee'),
        ),
    ]
