# Generated by Django 4.2.11 on 2024-05-02 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('Notes', '0003_note_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee'),
        ),
    ]
