# Generated by Django 4.2.11 on 2024-04-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepingBag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepingbags',
            name='date_of_received',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sleepingbags',
            name='is_washed',
            field=models.BooleanField(default=True),
        ),
    ]
