# Generated by Django 4.2.11 on 2024-04-29 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
        ('SleepingBag', '0002_sleepingbags_date_of_received_sleepingbags_is_washed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepingbags',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Location.location'),
        ),
    ]
