# Generated by Django 4.2.11 on 2024-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepingBag', '0003_sleepingbags_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepingbags',
            name='is_in_facility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sleepingbags',
            name='last_washing_cycle',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sleepingbags',
            name='date_of_received',
            field=models.DateField(auto_now_add=True),
        ),
    ]
