# Generated by Django 4.2.11 on 2024-04-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepingBag', '0004_sleepingbags_is_in_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepingbags',
            name='status',
            field=models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=4),
        ),
    ]
