# Generated by Django 4.2.11 on 2024-05-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0001_initial'),
        ('SleepingBag', '0005_alter_sleepingbags_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepingbags',
            name='linked_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Participant.participant'),
        ),
    ]
