# Generated by Django 4.2.11 on 2024-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepingBag', '0006_sleepingbags_linked_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepingbags',
            name='status',
            field=models.CharField(choices=[('Good', 'Goed'), ('Damaged', 'Beschadigd'), ('Lost', 'Verloren'), ('Bad', 'Slecht')], max_length=10),
        ),
    ]
