# Generated by Django 4.2.11 on 2024-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepingBag', '0007_alter_sleepingbags_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepingbags',
            name='date_of_received',
            field=models.DateField(auto_now_add=True, verbose_name='Datum van ontvangst'),
        ),
        migrations.AlterField(
            model_name='sleepingbags',
            name='is_in_facility',
            field=models.BooleanField(default=True, verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='sleepingbags',
            name='is_washed',
            field=models.BooleanField(default=True, verbose_name='Is gewassen'),
        ),
        migrations.AlterField(
            model_name='sleepingbags',
            name='last_washing_cycle',
            field=models.DateField(auto_now=True, verbose_name='Laatst gewassen'),
        ),
        migrations.AlterField(
            model_name='sleepingbags',
            name='status',
            field=models.CharField(choices=[('Good', 'Goed'), ('Damaged', 'Beschadigd'), ('Lost', 'Verloren'), ('Bad', 'Slecht')], max_length=10, verbose_name='Status'),
        ),
    ]
